apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
spec:
  containers:
    - name: httpd
      image: httpd:latest
      resources:
       requests:
        memory: "64Mi"
        cpu: "250m"
       limits:
        memory: "128Mi"
        cpu: "500m"
    - name: sidecar
      image: alpine
      resources:
       requests:
        memory: "64Mi"
        cpu: "250m"
       limits:
        memory: "128Mi"
        cpu: "500m"
      args:
        - sleep
        - 1d
  initContainers:
    - name: init1
      image: alpine
      args:
        - sleep
        - 5s
    - name: init2
      image: alpine
      args:
        - sleep
        - 5s
