apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  annotations:
    kubernetes.io/change-cause: "initial deployment"
spec:
  minReadySeconds: 10
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  strategy: 
   type: RollingUpdate
   rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
