apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
    schedule: "*/3 * * * *"
    jobTemplate:
      metadata:
       name: dummy-job
      spec:
        template:
          metadata:
            name: dummy-po
          spec:
            containers:
            - name: alp
              image: alpine
              command: 
                - sleep
                - "60"
            restartPolicy: OnFailure

