---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rs
  labels:
    app: httpd
    env: dev
spec:
 minReadySeconds: 10
 replicas: 5
 selector: 
  matchLabels: 
   app: httpd
   env: dev
   version: v1
 template:  
  metadata:
   labels:
    app: httpd
    version: v1
    env: dev
  spec:
   containers:
     - name: web
       image: httpd:latest
       resources:
       requests:
        memory: "64Mi"
        cpu: "250m"
       limits:
        memory: "128Mi"
        cpu: "500m"
       ports:
        - containerPort: 80
   
